name: deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - uses: s-weigand/setup-conda@v1
      - run: conda --version
      - run: which python

      - name: Install dependencies
        run: |
          conda install ipykernel
          python -m ipykernel install --user --name ai --display-name "ai"
          conda install -c glueviz glueviz
          pip install --upgrade setuptools
          pip install sphinx-intl
          pip install -r requirements.txt
          pip install sphinxcontrib-websupport
          pip install jupyter-book

      - name: Build the book
        run: |
          cd docs
          jb build --builder custom --custom-builder gettext --path-output _gettext .
          rm -rf _gettext/_build/.jupyter_cache/ _gettext/_build/jupyter_execute 
          rm -rf _gettext/_build/.doctrees
          sphinx-intl update -p _gettext/_build/gettext -l zh_CN
          jb build .

      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
